# Generated by Django 5.2.8 on 2025-12-02 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título do Vídeo')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('link', models.URLField(blank=True, null=True, verbose_name='Link do YouTube/Vimeo')),
                ('arquivo', models.FileField(blank=True, null=True, upload_to='videos/', verbose_name='Arquivo de Vídeo')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Vídeo',
                'verbose_name_plural': 'Vídeos',
                'ordering': ['-criado_em'],
            },
        ),
    ]
