# Generated by Django 5.2.8 on 2025-12-02 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0002_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='videos/capas/', verbose_name='Capa do Vídeo'),
        ),
    ]
