# Generated by Django 6.0 on 2025-12-10 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0003_video_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='anonimo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='perfil',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='perfil/'),
        ),
    ]
