# Generated by Django 6.0 on 2025-12-10 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0004_perfil_anonimo_perfil_foto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assunto',
            options={},
        ),
        migrations.AddField(
            model_name='assunto',
            name='imgfile',
            field=models.CharField(default='default', max_length=100),
        ),
        migrations.AlterField(
            model_name='assunto',
            name='nome',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='assunto',
            name='slug',
            field=models.SlugField(max_length=120, unique=True),
        ),
    ]
