# Generated by Django 5.2.5 on 2025-10-11 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0006_noticia_resumo'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='visualizacoes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
