# Generated by Django 5.2.5 on 2025-10-22 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0007_noticia_visualizacoes'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='noticia',
            name='autor',
            field=models.CharField(blank=True, default='JC', max_length=120),
        ),
        migrations.AddField(
            model_name='noticia',
            name='credito_imagem',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
