# Generated by Django 5.2.7 on 2025-11-12 19:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0009_perfil'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Enquete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pergunta', models.CharField(help_text='A pergunta da enquete.', max_length=255)),
                ('noticia', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='enquete', to='noticias.noticia')),
                ('votou_em', models.ManyToManyField(blank=True, related_name='enquetes_votadas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Opcao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto_opcao', models.CharField(max_length=100)),
                ('votos', models.IntegerField(default=0, help_text='Contador de votos para esta opção.')),
                ('enquete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opcoes', to='noticias.enquete')),
            ],
        ),
    ]
