# Generated by Django 5.2.7 on 2025-11-12 20:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0010_enquete_opcao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enquete',
            name='pergunta',
        ),
        migrations.RemoveField(
            model_name='enquete',
            name='votou_em',
        ),
        migrations.AddField(
            model_name='enquete',
            name='opcao_a',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Opção A'),
        ),
        migrations.AddField(
            model_name='enquete',
            name='opcao_b',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Opção B'),
        ),
        migrations.AddField(
            model_name='enquete',
            name='titulo',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Título da enquete'),
        ),
        migrations.AlterField(
            model_name='enquete',
            name='noticia',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enquete', to='noticias.noticia'),
        ),
        migrations.DeleteModel(
            name='Opcao',
        ),
    ]
