# Generated by Django 5.2.7 on 2025-11-17 21:34

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SudokuPuzzle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('difficulty', models.CharField(choices=[('easy', 'Fácil'), ('medium', 'Médio'), ('hard', 'Difícil')], max_length=10)),
                ('problem_board', models.CharField(max_length=81)),
                ('solution_board', models.CharField(max_length=81)),
            ],
            options={
                'unique_together': {('date', 'difficulty')},
            },
        ),
        migrations.CreateModel(
            name='UserSudokuProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_puzzle_date', models.DateField(default=django.utils.timezone.localdate)),
                ('completed_easy', models.BooleanField(default=False)),
                ('completed_medium', models.BooleanField(default=False)),
                ('completed_hard', models.BooleanField(default=False)),
                ('easy_completion_time', models.DurationField(blank=True, null=True)),
                ('medium_completion_time', models.DurationField(blank=True, null=True)),
                ('hard_completion_time', models.DurationField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sudoku_progress', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
