# Generated by Django 5.2.7 on 2025-10-20 18:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sudoku', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sudokupuzzle',
            name='date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name='usersudokuprogress',
            name='last_puzzle_date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
