# Generated by Django 5.2.7 on 2025-10-28 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sudoku', '0002_alter_sudokupuzzle_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersudokuprogress',
            old_name='completed_difficult',
            new_name='completed_hard',
        ),
        migrations.RenameField(
            model_name='usersudokuprogress',
            old_name='difficult_completion_time',
            new_name='hard_completion_time',
        ),
    ]
