# Generated by Django 6.0 on 2025-12-10 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sudoku', '0002_assunto'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Assunto',
        ),
    ]
