# Generated by Django 5.2.7 on 2025-10-28 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sudoku', '0003_rename_completed_difficult_usersudokuprogress_completed_hard_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sudokupuzzle',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'Fácil'), ('medium', 'Médio'), ('hard', 'Difícil')], max_length=10),
        ),
    ]
