# Generated by Django 5.2.5 on 2025-11-11 01:20

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('noticias', '0009_perfil'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CacaPalavras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dificuldade', models.CharField(choices=[('facil', 'Fácil'), ('medio', 'Médio'), ('dificil', 'Difícil')], max_length=10)),
                ('palavras_chave', models.JSONField(default=list)),
                ('grade', models.JSONField(blank=True, default=list)),
                ('data', models.DateField(default=django.utils.timezone.now)),
                ('noticia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='noticias.noticia')),
                ('tema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='noticias.assunto')),
            ],
            options={
                'unique_together': {('tema', 'dificuldade', 'data')},
            },
        ),
        migrations.CreateModel(
            name='ProgressoJogador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel_atual', models.PositiveSmallIntegerField(default=1)),
                ('concluido', models.BooleanField(default=False)),
                ('links_conquistados', models.JSONField(default=list)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('tema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='noticias.assunto')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('usuario', 'tema')},
            },
        ),
    ]
