# Generated by Django 6.0 on 2025-12-10 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caca_links', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
            ],
        ),
    ]
