# Generated by Django 5.2.7 on 2025-11-12 01:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caca_links', '0001_initial'),
        ('noticias', '0009_perfil'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='progressojogador',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='progressojogador',
            name='tema',
        ),
        migrations.RemoveField(
            model_name='progressojogador',
            name='usuario',
        ),
        migrations.CreateModel(
            name='CacaPalavra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.JSONField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('noticia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cacapalavras', to='noticias.noticia')),
                ('tema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cacapalavras', to='noticias.assunto')),
            ],
        ),
        migrations.DeleteModel(
            name='CacaPalavras',
        ),
        migrations.DeleteModel(
            name='ProgressoJogador',
        ),
    ]
