# Generated by Django 5.2.7 on 2025-11-12 19:22

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caca_links', '0002_alter_progressojogador_unique_together_and_more'),
        ('noticias', '0009_perfil'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cacapalavra',
            options={'ordering': ['-data', 'tema', 'dificuldade'], 'verbose_name': 'Caça-palavra', 'verbose_name_plural': 'Caça-palavras'},
        ),
        migrations.AddField(
            model_name='cacapalavra',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='cacapalavra',
            name='data',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Data de geração'),
        ),
        migrations.AddField(
            model_name='cacapalavra',
            name='dificuldade',
            field=models.CharField(choices=[('facil', 'Fácil'), ('medio', 'Médio'), ('dificil', 'Difícil')], default='facil', max_length=10, verbose_name='Dificuldade'),
        ),
        migrations.AddField(
            model_name='cacapalavra',
            name='palavras_chave',
            field=models.JSONField(blank=True, default=list, verbose_name='Palavras-chave'),
        ),
        migrations.AlterField(
            model_name='cacapalavra',
            name='grade',
            field=models.JSONField(blank=True, default=list, verbose_name='Grade do caça-palavras'),
        ),
        migrations.AlterField(
            model_name='cacapalavra',
            name='noticia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cacas_palavras', to='noticias.noticia', verbose_name='Notícia'),
        ),
        migrations.AlterField(
            model_name='cacapalavra',
            name='tema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cacas', to='noticias.assunto', verbose_name='Tema'),
        ),
    ]
