# Generated by Django 6.0 on 2025-12-10 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('caca_links', '0002_tema'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tema',
        ),
    ]
